import { useAuth0 } from '@auth0/auth0-react';

/**
 * LandingPage — Shown to unauthenticated users.
 * Professional dark hero with feature grid and CTAs.
 */
function LandingPage() {
  const { loginWithRedirect } = useAuth0();

  const handleSignUp = () =>
    loginWithRedirect({ authorizationParams: { screen_hint: 'signup' } });

  const handleLogin = () => loginWithRedirect();

  const features = [
    {
      icon: '🧠',
      title: 'AI-Generated Courses',
      desc: 'Full course outlines with modules and lessons generated by Gemini AI in seconds.',
    },
    {
      icon: '🎯',
      title: 'Interactive Quizzes',
      desc: 'MCQ quizzes with instant feedback to test your understanding of each lesson.',
    },
    {
      icon: '🎧',
      title: 'Hinglish Audio',
      desc: 'Get an AI-generated audio summary of any lesson in Hinglish for easier retention.',
    },
    {
      icon: '📄',
      title: 'PDF Export',
      desc: 'Download full courses or individual lessons as beautifully formatted PDFs.',
    },
    {
      icon: '▶️',
      title: 'Video Integration',
      desc: 'Curated YouTube videos embedded directly into your lessons for visual learning.',
    },
    {
      icon: '🔒',
      title: 'Secure & Personal',
      desc: 'Auth0-powered authentication keeps your courses private and securely linked to you.',
    },
  ];

  return (
    <div className="min-h-screen bg-[#0f172a] flex flex-col font-sans overflow-y-auto">

      {/* ── Navigation ──────────────────────────────────────────────────────── */}
      <header className="flex items-center justify-between px-6 sm:px-10 py-4 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center">
            <svg className="w-4.5 h-4.5 text-white" width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
          </div>
          <span className="text-white font-bold text-lg tracking-tight">
            Text<span className="text-indigo-400">To</span>Learn
          </span>
        </div>
        <div className="flex items-center gap-2.5">
          <button
            onClick={handleLogin}
            className="px-4 py-1.5 text-sm font-medium text-slate-300 hover:text-white border border-slate-700 hover:border-slate-500 rounded-md transition-all duration-150"
          >
            Log In
          </button>
          <button
            onClick={handleSignUp}
            className="px-4 py-1.5 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-500 rounded-md transition-all duration-150 shadow-sm"
          >
            Sign Up Free
          </button>
        </div>
      </header>

      {/* ── Hero ────────────────────────────────────────────────────────────── */}
      <main className="flex-1 flex flex-col items-center">
        <section className="w-full max-w-4xl mx-auto text-center px-6 pt-20 pb-16">

          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 mb-8 rounded-full bg-indigo-950 border border-indigo-800 text-xs font-semibold text-indigo-300">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-pulse" />
            Powered by Google Gemini AI
          </div>

          {/* Headline */}
          <h1 className="text-5xl sm:text-6xl font-extrabold text-white mb-5 leading-[1.1] tracking-tight">
            Master Any Topic<br />
            <span className="bg-gradient-to-r from-indigo-400 to-violet-400 bg-clip-text text-transparent">
              in Minutes
            </span>
          </h1>

          {/* Sub-headline */}
          <p className="text-slate-400 text-lg sm:text-xl max-w-2xl mx-auto leading-relaxed mb-10">
            Generate complete, structured AI courses on any subject — with modules, quizzes,
            embedded videos, and audio summaries — instantly.
          </p>

          {/* CTA Row */}
          <div className="flex flex-wrap items-center justify-center gap-3 mb-16">
            <button
              onClick={handleSignUp}
              className="px-7 py-3 text-base font-semibold text-white bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 rounded-lg shadow-lg shadow-indigo-900/50 transition-all duration-150"
            >
              Start Learning Free →
            </button>
            <button
              onClick={handleLogin}
              className="px-7 py-3 text-base font-semibold text-slate-300 hover:text-white border border-slate-700 hover:border-slate-500 rounded-lg transition-all duration-150"
            >
              Log In
            </button>
          </div>

        </section>

        {/* ── Feature Grid ────────────────────────────────────────────────────── */}
        <section className="w-full max-w-5xl mx-auto px-6 pb-20">
          <p className="text-center text-[10px] font-bold uppercase tracking-widest text-slate-600 mb-6">
            Everything you need to learn smarter
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((f) => (
              <div
                key={f.title}
                className="flex flex-col gap-2.5 p-5 rounded-xl border border-slate-800 bg-slate-900/50 hover:border-indigo-800 hover:bg-indigo-950/20 transition-all duration-200 group"
              >
                <span className="text-2xl">{f.icon}</span>
                <h3 className="text-sm font-bold text-white group-hover:text-indigo-300 transition-colors">
                  {f.title}
                </h3>
                <p className="text-xs leading-relaxed text-slate-500 group-hover:text-slate-400 transition-colors">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* ── Footer ──────────────────────────────────────────────────────────── */}
      <footer className="text-center py-5 border-t border-slate-800 text-xs text-slate-600">
        © {new Date().getFullYear()} TextToLearn &nbsp;·&nbsp; Built for learning, powered by AI
      </footer>
    </div>
  );
}

export default LandingPage;
